# fly.toml app configuration file generated for wook-remix on 2024-05-12T18:22:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wook-remix'
primary_region = 'atl'

[env]
  # AUTH0_CALLBACK_URL is a secret
  # AUTH0_CLIENT_ID is a secret
  # AUTH0_CLIENT_SECRET is a secret
  # AUTH0_DOMAIN is a secret
  # AUTH0_AUDIENCE is a secret
  # AUTH0_RETURN_TO_URL is a secret
  # AUTH0_LOGOUT_URL is a secret
  # COOKIE_SECRET is a secret
  WOOK_API_BASE_URL = "https://wook-status-article-data.fly.dev"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
